### ISSUE TITLE
Services can hardcode / specify their own getRequestSizeLimit()

### ISSUE THREAD

**Issue by TylerBreau** [breautek/storm#4]
Services should never specify their own getRequestSizeLimit(). This value should always be obtained from the configuration files.

**Comment by breautek** [comment]
Agreed, the current default of `5242880` should be inside the defaults configuration file and configurable via `bt-config.json` or `bt-local-config.json`.

The method should remain public and overridable if the concrete class wishes to do so. But preferably should be using configs.

**Comment by breautek** [comment]
I've changed my mind... `getRequestSizeLimit` should be removed in favour for configs.

**Comment by breautek** [comment]
I updated `getRequestSizeLimit` to by default, return a value from the config. Therefore it is still overridable thus it won't be a breaking change, but applications should avoid overriding the method.
